[package]
name = "oiio-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.107"

[build-dependencies]
anyhow = "1.0"
cxx-build = "1.0.107"
